// Auth actions
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

// Media actions
export const MEDIA_UPLOAD_START = "MEDIA_UPLOAD_START";
export const MEDIA_UPLOAD_SUCCESS = "MEDIA_UPLOAD_SUCCESS";
export const MEDIA_UPLOAD_FAIL = "MEDIA_UPLOAD_FAIL";
export const MEDIA_RETRIEVE_START = "MEDIA_RETRIEVE_START";
export const MEDIA_RETRIEVE_SUCCESS =
	"MEDIA_RETRIEVE_SUCCESS";
export const MEDIA_RETRIEVE_FAIL = "MEDIA_RETRIEVE_FAIL";
export const MEDIA_DELETE_START = "MEDIA_DELETE_START";
export const MEDIA_DELETE_SUCCESS = "MEDIA_DELETE_SUCCESS";
export const MEDIA_DELETE_FAIL = "MEDIA_DELETE_FAIL";
export const MEDIA_UPDATE_START = "MEDIA_UPDATE_START";
export const MEDIA_UPDATE_SUCCESS = "MEDIA_UPDATE_SUCCESS";
export const MEDIA_UPDATE_FAIL = "MEDIA_UPDATE_FAIL";

// Post actions
export const POST_UPLOAD_START = "POST_UPLOAD_START";
export const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";
export const POST_UPLOAD_FAIL = "POST_UPLOAD_FAIL";
export const POST_RETRIEVE_START = "POST_RETRIEVE_START";
export const POST_RETRIEVE_SUCCESS =
	"POST_RETRIEVE_SUCCESS";
export const POST_RETRIEVE_FAIL = "POST_RETRIEVE_FAIL";
export const POST_DELETE_START = "POST_DELETE_START";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
export const POST_UPDATE_START = "POST_UPDATE_START";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";

// User actions
export const USER_RETRIEVE_START = "USER_RETRIEVE_START";
export const USER_RETRIEVE_SUCCESS =
	"USER_RETRIEVE_SUCCESS";
export const USER_RETRIEVE_FAIL = "USER_RETRIEVE_FAIL";
export const USER_UPDATE_START = "USER_UPDATE_START";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_DELETE_START = "USER_DELETE_START";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_UPLOAD_START = "USER_UPLOAD_START";
export const USER_UPLOAD_SUCCESS = "USER_UPLOAD_SUCCESS";
export const USER_UPLOAD_FAIL = "USER_UPLOAD_FAIL";
export const USER_COUNT_START = "USER_COUNT_START";
export const USER_COUNT_SUCCESS = "USER_COUNT_SUCCESS";
export const USER_COUNT_FAIL = "USER_COUNT_FAIL";
